### ISSUE TITLE
关于端口转发的问题

### ISSUE THREAD

**Issue by WuYunlong** [joyqi/socket-pipe#1]
``` bash
# 如果服务端启动命令为
socket-pipe -l 10080 -r 80 -t hserver -s ng

# 客户端启动命令为
socket-pipe -l 80 -r 123.123.123.123@10080 -t hclient -s ng
```
此时一切正常， 我可以通过访问 ng.domain.com 访问本机

``` bash
# 修改服务端命令
socket-pipe -l 10080 -r 8080 -t hserver -s ng

客户端启动命令为
socket-pipe -l 80 -r 123.123.123.123@10080 -t hclient -s ng
```
此时访问ng.domain.com出错，
访问 ng.domain.com:8080 正常 可以访问本机

请问能否做到服务端代理的端口为8080 但是可以直接通过 ng.domain.com 访问本机的80端口

我现在的操作是 用了nginx 做代理 

``` bash
upstream ng {
    server 127.0.0.1:8080;
    keepalive 64;
}
server {
    listen 80;
    server_name *.domain.com;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host:80;
        proxy_set_header X-Nginx-Proxy true;
        proxy_set_header Connection "";
        proxy_pass http://ng;
    }
}
```

**Comment by joyqi** [comment]
看到你已经关闭了issue，补充一下，如果你要直接通过域名且隐藏端口号访问一个地址，那么只有一种情况能满足，即这个地址的端口号是80

**Comment by WuYunlong** [comment]
很开心收到你的回复

这个问题我已经解决掉了 就是因为nginx反向代理 把进来的80端口直接反向代理到8080端口
之前写的是 127.0.0.1:8080 是有问题的 现在修改为
0.0.0.0:8080 这样就解决了这个问题

现在我在研究这个东西 因为对tpc udp 这些了解甚少 之前接触过 ngrok 但是使用 ngrok 一直很不稳定
那天在掘金开到了你的文章所以使用了socket-pipe 目前效果还不错

关于这个我这边现在还有一个需求 就是能否和 ngrok 一样有一个本地调试的界面能看到那些请求和进来携带了那些参数
和 ngrok 一样能在本地开启 127.0.0.1:4040 这样直接访问就能看到数据的请求。

我是做PHP的 公司目前项目大多数基于微信做服务，如果没有这个 http 代理的话做调试会变的十分费劲，现在有了这个但是在调试过程中有很难看到参数
还要一堆一堆的echo print_r file_put_contnets 调试起来比较费事

另外对于这个http反向代理 我们是否支持流量统计呢 如果要实现流量统计(不同的子域名)进行统计，有没有什么好的方案。

**Comment by joyqi** [comment]
参数这个倒是很好加，流量统计这种需求太小众了，可能暂时不会开发

**Comment by WuYunlong** [comment]
嗯期待这个查看参数的功能上线
目前基于这个socket-pipe做了一个客户端 用了electron 
刚刚起步的样子
现在就发现功能略显单薄
这样的话大家就都能很简单的使用 http udp tcp 做内网穿透了
